name: "Check Manifest"

on: [push]
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        # scipy and cython are required to build sdist
        run: |
          python -m pip install --upgrade pip
          pip install check-manifest scipy cython         
        shell: bash
      - run: |
          check-manifest -v --ignore "sklearn/linear_model/_sag_fast.pyx,sklearn/utils/_seq_dataset.pxd,sklearn/utils/_seq_dataset.pyx"
        shell: bash
